Fuco1/smartparens

- smartparens.el
If `sp-use-subword` (a new defcustom) is non-nil and `subword-mode` is active, `sp-kill-word` and `sp-backward-kill-word` will only kill "subwords".
To preserve existing behavior, `sp-use-subword` is nil by default.
Is this a behavior you'd be interested in adding? Does this look like a reasonable way to go about it?
Thanks!
> Add optional subword-mode support

- smartparens.el
See https://github.com/clojure-emacs/inf-clojure/blob/master/inf-clojure.el
> Add inf-clojure-mode to sp--lisp-modes

- smartparens.el
> Add hooks to limit searching within bounds.

- smartparens-config.el
- smartparens-haskell.el
Ok there's my first stab at it. Didn't know what you wanted to do with regards to the file header so I left that blank. This should resolve #424
> First stab at matching haskell comment blocks

- smartparens.el
@Fuco1 
This should be pretty self explanatory. Should fix #360. Should supersede #443.
> Enable CUA shift selection with smartparens motions

- Cask
- smartparens-config.el
- smartparens-rust.el
- test/smartparens-rust-test.el
> Handle ' in rust-mode intelligently.

- smartparens.el
- test/smartparens-python-test.el
- test/smartparens-slurp-test.el
Fixes #534.
Let me know what you think of this approach. I've added tests, so I think the code is sane, but it's quite possible I've missed corner cases.
> When slurping forward, don't include punctuation at end of line.

- smartparens-python.el
- test/smartparens-python-test.el
> Fix python-indent-dedent-line-backspace in strict mode

- Cask
- README.md
- test/test-helper.el
It would be nice to track coverage with our tests, so I've set up code coverage. Let me know what you think :)
You can see an example of the coverage data here: https://coveralls.io/github/Wilfred/smartparens
> Add code coverage

- smartparens.el
> Typo in a var name

- Cask
- smartparens-clojure.el
- test/smarparents-clojure-test.el
Make 'sp-sexp-prefix' aware of Clojure constructs.
> [#593] Add smartparens-clojure.el

- smartparens.el
> Limit binding of case fold search

- smartparens-latex.el
The title says it all. I had to write lots of norms lately so I added another local pair.
> Add local pair for norm bars

- smartparens-latex.el
See https://github.com/Fuco1/smartparens/pull/631#issuecomment-258503987
> Fix whitespace insertion when slurping in LaTeX

- Cask
- smartparens-elixir.el
- test/smartparens-elixir-test.el
> Add elixir-lang support

- smartparens-elixir.el
The code that check for code blocks missed some special forms. I think I got them all.
> Added some missing special forms for the Elixir mode

- smartparens-ess.el
I'm not super familiar with smartparens, but this seems to fix #745 for me.
> Fix apostrophe in ESS comments

- smartparens-clojure.el
- smartparens-config.el
- smartparens-elixir.el
- smartparens-ess.el
- smartparens-haskell.el
- smartparens-html.el
- smartparens-javascript.el
- smartparens-latex.el
- smartparens-lua.el
- smartparens-markdown.el
- smartparens-ml.el
- smartparens-org.el
- smartparens-python.el
- smartparens-racket.el
- smartparens-ruby.el
- smartparens-rust.el
- smartparens-scala.el
- smartparens-text.el
It was already in use in smartparens.el, this adds it to the mode
specific files too.
> Use lexical-binding in all files

- smartparens-config.el
Sorry, the last pr I did not add crystal to the configuration.
> Add crystal to config

- smartparens-racket.el
Nothing should be done for single quotes in racket.
> Add treatment of single quotes for racket

- smartparens.el
> [#889] Don't grab C-g if highlighting is disabled

- smartparens.el
Gerbil is a scheme on top of Gambit, see https://github.com/vyzo/gerbil.
> add gerbil (scheme) to sp-lisp-modes

- smartparens.el
> Add `sp-show-pair-match-priority` option

- smartparens-rust.el
> add rustic to rust modes

- smartparens-config.el
- https://github.com/Fuco1/smartparens/pull/998
> Make sure smartparens-rust loaded in rustic-mode

- smartparens-config.el
This fixes auto loading of the rust config for `rustic`.
> The package is called `rustic` and not `rustic-mode`

- smartparens-c.el
> fix C comments

- smartparens.el
This should speed up responsiveness without the Quit bug. See #943 and #946.
> Use while-no-input from Emacs 27

- smartparens-python.el
I'm slowly upstreaming various helpers from my Emacs config. This one I've used for a few years I think. Never was getting any misses *(the context for function definition in python is pretty unambiguous)*, so barring something I might have missed while preparing the code for upstreaming, this should be safe.
> smartparens-python.el: auto-insert a colon in function definitions

- smartparens-config.el
- smartparens-erlang.el
This patch adds support for EDoc verbatim quoting for Erlang comments.
> Fix #1135 Add support for EDoc verbatim quoting for erlang comments

- smartparens-config.el
- smartparens-unison.el
Disable pair actions for single quotes in unison, assuming the [unisonlang-mode](https://github.com/dariooddenino/unison-mode-emacs) major mode.
> feat(unison): disable closing single quotes

- smartparens-config.el
- smartparens-lua.el
https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=b6659e98a4fcaa44477b64d7782243feca020418
> Add support for lua-ts-mode
