Fuco1/smartparens

- smartparens.el
- tests/smartparens-test.el
The following edge-cases have been fixed:
* Regions that were trivially ok because they didn't contain any opening
or closing pairs.
* Regions containing an unbalanced string.
Closes #405
> Improve sp-region-ok-p

- smartparens-config.el
Note: I didn't add a sp--python-modes variable since python.el and python-mode.el both provide python-mode, so that wouldn't make sense.
>  support python.el as well as python-mode.el

- smartparens.el
This function had issues with relative cursor position which made it distance itself further and further from original context. This is fixed version, as well as taking some liberties in deciding what most useful context would be. 
The behavior of `sp-get-sexp` responsible for choosing its targets reflects on this command in a way that delimits its usefulness. Especially in the root context, where `sp-get-enclosing-sexp` doesn't shine with efficiency either.
> sp-clone-sexp will no longer dash ahead.

- smartparens.el
The functions `sp--search-{forward,backward}-regexp` appear to have had
their bounds reversed.
Does the seem right to you, @tmccombs?
> Fix point at wrong side of bound error

- smartparens.el
Indentation in [coffee-mode](https://github.com/defunkt/coffee-mode) is not very smart, it just cycles through possible indentations. So automatically reindenting after a kill mostly results in a correctly indented line becoming incorrectly indented.
This is an attempt to fix that behavior. If there is another, better way to do it, please let me know!
> Don't reindent after kill for some modes.

- smartparens-scala.el
noddy copy of python-fix for the 
{|} this.that.theother     -> {this. that.}  theother
issue
> smartparens defaults for scala-mode

- smartparens.el
These are used in quack for parentheses and brackets.
Fixes #502
> Add special insert commands for quack

- smartparens.el
These are used in racket-mode for inserting parens, brackets and braces.
> Add special insert commands for racket-mode

- smartparens.el
When in normal and visual states in `evil`, it doesn't make sense to respect `sp-show-pair-from-inside`.  Change shows matches in normal and visual states matching the pair under the cursor.  This also ensures `evil-jump-item` or `%` will always move to the pair show-paren is highlighting.
> Always show matching paren over cursor in `evil-mode`

- smartparens.el
Until #493 is resolved, this should make some Haskellers happy.
---
Often in refactoring we remove parentheses in Haskell, e.g. in this case using `sp-splice-sexp`, but haskell-mode indentation suffers from the same problem for that we have had in `sp-kill-sexp`. For example:
```haskell
import Control.Monad
import System.Directory
import System.FilePath
main = do
content <- getDirectoryContents "."
forM_ content $ \filename -> do
let filenameInDir = ("." </> filename)
print filenameInDir
```
Before this change, `sp-splice-sexp` inside the parentheses would result in:
```haskell
forM_ content $ \filename -> do
let filenameInDir = "." </> filename
print filenameInDir
```
Which breaks compilation. It should be:
```haskell
forM_ content $ \filename -> do
let filenameInDir = "." </> filename …
```
> sp-splice-sexp: also avoid indenting here on certain modes

- smartparens-haskell.el
`comint-last-prompt` has superseed `comint-last-prompt-overlay` in recent Emacs versions.
> Use `comint-last-prompt' in smartparens-haskell

- smartparens-config.el
- smartparens.el
Otherwise, this can lead to very hard-to-debug errors.
Consider the code:
(defun always-true (id context)
t)
(sp-with-modes '(some-mode)
(sp-local-pair "[" "]" :unless '(always-true)))
We would expect [ to never be automatically paired. However,
`always-true` only takes 2 arguments, when it should take 3. As a
result, we swallow the error and consider `always-true` to have returned
nil!
This made my debugging tricky, so I believe throwing the error
sooner is the right thing to do here.
> Don't ignore errors when running :when and :unless functions.

- smartparens.el
aggressive-indent-mode [1] already provides support for re-indentation
after buffer changes, and it does it more sophisticated than just
calling indent-region (and additionally, it won't issue an annoying
"Indenting region..." message).  Therefore, if aggressive-indent-mode is
enabled in the current buffer, don't indent the region but let the job
be done by that.
[1] https://github.com/Malabarba/aggressive-indent-mode
> Don't indent if aggressive-indent-mode is enabled

- Makefile
- README.md
Document how to run tests, and remove the remaining bits of ecukes.
Closes #515.
> Clarify testing.

- smartparens-rust.el
- test/smartparens-rust-test.el
Minor bug, added a test case.
@Fuco1 is this sufficiently boring that you're happy with me committing directly into master, or do you prefer PRs for fixes like this?
> Ensure that we can kill Rust words at the beginning of a buffer.

- smartparens.el
This should help us to debug when this function is erroring, and will
ensure that Emacs does not remove the handler unexpectedly.
#481
> Catch errors when running sp--post-self-insert-hook-handler

- smartparens-rust.el
- test/smartparens-rust-test.el
This fixes an oversight in pairing angle brackets in Rust when parameterizing function calls, such as `iterator.collect::<Vec<u32>>()`.
By the way, thank you for this excellent package. :smile:
> Pair < with > in parameterized Rust function calls.

- smartparens-python.el
- test/smartparens-python-test.el
Hi @Fuco1
This is just applying the fix you suggested for #236. I think just doing `(` and `[` is reasonable here. I think the code is correct. It's using dynamic scoping so generates a warning, but it does pass the tests.
I've also committed 62429854f7ea919b9610bacb282e756f0bc5befc to make hybrid slurping more discoverable.
> Don't insert whitespace when slurping in Python.

- smartparens-python.el
- test/smartparens-python-test.el
Fixes #573 and adds a test.
@Fuco1 I'm not sure if this is the right approach. The naive implementation we had before didn't work, but I'm not sure if this is a bug in the smartparens parsing.
```python
x = |
x = '|
```
Is there a better approach? Moving around and calling `syntax-ppss` seems hacky but I can't see a better way using just `id` `context` and `action`.
> Ensure that we pair ' in code in Python.

- smartparens.el
- test/smartparens-commands-test.el
This pull request includes:
* Tests for `sp-kill-sexp` based on the examples in the docstring
* A fix for a bug I found when testing those examples (SP is confused about negative prefix arguments)
* A fix for #572 (handling punctuation) by starting the kill from the current point position
I've not explored this part of the code before, so please let me know if I've done anything silly :)
>  Bugfixes and improvements to `sp-kill-sexp`

- smartparens.el
- test/smartparens-commands-test.el
> sp-select-next-thing should handle buffer limits gracefully.

- smartparens-ruby.el
motion-mode (used primarily for rubymotion) is a derived major mode of ruby-mode.
> Add smartparens support for motion-mode.

- Cask
- smartparens-config.el
- smartparens-ess.el
- test/smartparens-ess-test.el
Hi!
Following up [our recent conversation](https://github.com/mutbuerger/smartparens-ess/issues/1), I'd like to add the extension for `ess-mode`. Loading `ess-site` for testing is tricky but should work as well.
> Add extension for ESS

- smartparens-rust.el
- test/smartparens-rust-test.el
Before this commit, closing chevrons were not autoskipped.  Typing:
`T<` would result in the correct insertion of a matching closing
chevron: `T<|>`, but typing `>` would not result in `T<>|>`, not
skipping the closing chevron even with the `autoskip` action set on the
pair.
This was caused by the regexp in `sp-rust-could-be-parameterized` set as
a `when` filter for the local pair "<" ">".  This filter is called by
`sp--do-action-p` not only when inserting a chevron, but also when
determining if the closing chevron should be autoskipped.  In the
closing case, the regexp does not match, because at the moment this
check is done the code contains one extra chevron: `<T>|>`.
This commits adds a ">" alternative to the regexp so that filter returns
true when `sp--do-action-p` is called for the …
> Fix autoskipping closing chevrons in rust-mode

- smartparens-clojure.el
- smartparens-config.el
- smartparens.el
Addresses #649 for Clojure-related modes.
> Match "`" with "`" in Clojure-related modes

- smartparens.el
This adds a new command `sp-mark-sexp` that is analogous to Emacs's builtin `mark-sexp`, but uses smartparens notion of sexp. It also adds a key binding (`C-M-SPC`) for it to `sp-smartparens-bindings`. The chosen is key binding is one of Emacs's defaults for `mark-sexp` ---just like `sp-smartparens-bindings` uses Emacs's defaults for `forward-sexp`, `kill-sexp`, etc.
> added sp-mark-sexp analogous to mark-sexp

- smartparens-rust.el
- test/smartparens-rust-test.el
Ensure that we can insert > in function signatures, or delete it in
comparisons and left shifts.
@Fuco1 I'm gradually learning the smartparens API, but handling all the different actions is tricky. I think this is correct, but I'd appreciate your review.
If you're too busy to review, I'll merge in a few days anyway, no stress.
> Support < and > in Rust with strict mode.

- smartparens.el
This should be a fix for #690. It at least stops the "end of buffer" problem... I'll have to keep testing to see if this has anything to do with the hanging that `C-g` was killing (that might be a jupyter ipython problem, because I haven't gotten it since switching to normal python repl).
> Fix backward-delete hang in comint when at end of last prompt

- .github/ISSUE_TEMPLATE.md
An issue template should cut down on the number of incomplete bug reports.
> Add GitHub issues template

- smartparens-config.el
- smartparens-ml.el
Rename smartparens-ocaml to smartparens-ml: The OCaml local pair
definitions apply for all ML based languages (like F#).
> Support fsharp-mode

- Cask
- smartparens.el
- test/smartparens-evil-test.el
Evil/Vim uses the 0 Register as the Yank Register. When yanking a
sexp, add the yanked text to the 0 Register too.
Added logic to add copied region to 0 Register like in Vim/Evil.
Added Register Prefix handling so that the yanked text goes into the
right place.
For example, this should be possible now.
"x (sp-copy-sexp)
:reg
0 Register and x register should contain the text that was copied.
https://github.com/Fuco1/smartparens/issues/724
Open to ideas on the Doc comment for the new function.
> Replace kill-fn with wrapper that accounts for Evil Yank/Registers

- smartparens-javascript.el
The fix you suggested worked so I am PR-ing it :smile: 
Thanks a lot!
I will probably do the same for `reason-mode`, which I am maintaining, at some point.
> Add typescript-mode to smartparens-javascript.el

- smartparens.el
- test/smartparens-skip-closing-pair-test.el
Don't inhibit inserting closing delimiters for pairs that don't use the `autoskip` action.
Commit a677859 added code to prevent closing delimiters from being inserted in strict mode. Typing a closing delimiter will either skip over the delimiter that was automatically inserted, or emit a message that an unbalanced delimiter was blocked from insertion. I think it makes sense to exempt from this pairs that don't use the `autoskip` action (and/or the `insert` action? more on that below), since in that case the only reason to type the closing delimiter is if you want to insert it.
I ran into this because, in C-like modes, I set up `{}` for the `navigate` and `wrap` actions, but not `insert` or `autoskip`.
It may also make sense to exempt pairs without the `insert` action, for basically the …
> Allow inserting closing delimiters for non-autoskip pairs

- smartparens.el
> Add backword delete word and symbol variant

- smartparens.el
This would address #705. Not really sure if this is the right way to go about this, but i think it wouldn't interfere with any smartparens operations, only setting the default to `hungry-delete-*` if hungry-delete-mode is on. 
Minimal testing seems to confirm this, though I'm sure I've only covered my biased subset of use cases.
> Handle hungry-delete-mode.

- smartparens.el
- test/smartparens-wrapping-test.el
When `delete-selection-mode` is on, typing a character with an active region will replace the region with the typed character.  However, smartparens advises `delete-selection-pre-hook` to inhibit this behavior when the typed character is part of a pair, as smartparens wants to wrap the region rather than replace it.
However, if you turn smartparens on and then back off in a buffer where `delete-selection-mode` is also on, this advice would prevent `delete-selection-pre-hook` from replacing the selection even though smartparens is not on, and therefore the region would be neither deleted nor wrapped.  This commit makes it so that the smartparens advice never affects `delete-selection-pre-hook` unless smartparens-mode is turned on.
Fixes #763.
> Don't affect delete-selection-mode when SP is off

- smartparens-elixir.el
- test/smartparens-elixir-test.el
Current configuration of smartparens for `elixir-mode` has problems with handling commas (`,`) during slurping and barfing. 
Example: 
I have stolen the solution from `scala-mode` which had the similar problem:
> Fix handling of commas during slurp and barf in elixir-mode

- smartparens-rust.el
- test/smartparens-rust-test.el
I'm writing a bunch of rust lately, and have run into a problem where I couldn't insert `=>` in strict mode. Soooo, this pull request adds a test & adjusts the pair logic to correctly work when `=>` is inserted in rust.
Hope this is acceptable - it looks like all rust tests are passing with this change (:
> In rust-mode, allow typing match branches (=>) in strict mode

- smartparens.el
There's an asymmetry in having `turn-on-smartparens-strict-mode` without having a corresponding `turn-off`.
> Add `turn-off-smartparens-strict-mode`

- smartparens.el
This is a small change to the ```delete-selection-pre-hook``` advice to avoid unnecessary computations.
I noticed sluggish responses when moving around some buffers; profiling revealed the advice to ```delete-selection-pre-hook``` to be the culprit. In particular, it repeatedly called ```sp-wrap--can-wrap-p```, which ate a large fraction of CPU time. With this patch, ```sp-wrap--can-wrap-p``` is only called when there actually is an active region. The additional condition is directly taken from ```delete-selection-pre-hook```; it is used there to decide whether to do something. With this small change, the problem of sluggish response times went away.
> Improve performance of delete-selection-pre-hook when no region is active

- smartparens.el
This ensures `sp-point-in-string` returns correctly when invoked from
`evil-smartparens` etc - see https://github.com/expez/evil-smartparens/issues/42
> Narrow in `sp-region-ok-p` after doing syntax checks

- smartparens.el
This command has the potential to create unmatched brackets if it is not remapped.
> Remap kill-whole-line in strict-mode

- smartparens.el
The need for this was eliminated in #671
> Remove cl package

- smartparens-elixir.el
- test/smartparens-elixir-test.el
Similar to 1bf46316 this prevents smartparens from inserting a `do`,`end` pair
when you type one of it's keywords inside a string.
> Do not insert elixir bracketed keywords in strings.

- smartparens.el
- test/smartparens-javascript-test.el
js2-jsx-mode is js2-mode with support for XML template literals, so symbol based operations work a bit differently from markup language specific modes.
This tweaks sp-get-thing so that it correctly detects XML tag boundaries and makes most HTML/SGML based functions work properly.
One caveat is that self-closing tags (`<Tag/>`) are not treated as expected, as markup language support in smartparens is based on SGML, not XML.
> Add support for HTML/SGML based functions in js2-jsx-mode

- smartparens.el
- test/smartparens-commands-test.el
Currently `sp-kill-whole-line` essentially does a balanced <kbd>C-a C-k </kbd> (delete contents of line up to newline) however kill-whole-line acts more like <kbd> C-a C-k C-k </kbd> (delete contents of line including newline.
I think the smartparens commands with similar names should try to mimic the builtin emacs commands. However this change will probably break the workflow of people who depended on the <kbd> C-a C-k </kbd> behaviour.
> Make sp-kill-whole-line remove the newline like kill-whole-line

- Cask
- smartparens-crystal.el
- test/smartparens-crystal-test.el
[Crystal](https://crystal-lang.org/) is a language that is almost identical to ruby's syntax. So add support, just copy smartparent-ruby.el, replace ruby globally, and add crystal private keywords.
> Support crystal

- smartparens.el
Keys `M-(`, `M-j`, and `M-?` are all bound by Paredit, and it was surprising to me when I switched to Smartparens and they weren't bound anymore.
> Add more entries to sp-paredit-bindings

- .gitignore
This allows people to customize directory-local variables for Smartparens without leaving unstaged changes or untracked files in the Git repository. (Support for `.dir-locals-2.el` is new in Emacs 26.)
> Add .dir-locals-2.el to .gitignore

- docs/example-configuration.rst
For a user coming to readthedocs, it is not immediately clear where the default configuration can be found (although she might guess that this place is also on Github ;-).
> Added link to default-configuration

- smartparens-ml.el
This is a short version of #886 It only removes pairs that are not pairs in ocaml and reason.
> disable ' and ` for ocaml and reasonml

- smartparens.el
`paren` gives you an overlay that matches pairs and their content if you set its matching style to `expression`. `smartparens` doesn't support this matching style therefore there is no way to highlight the content of a pair.
In this PR I'm proposing a new customizable face `sp-show-pair-match-content-face` that will operate solely on the contents of a pair. 
This has an advantage over the `paren` implementation as `paren` is too rigid in that it doesn't allow you to highlight pairs and their contents independently.
Here's a look at a possible configuration
And a working scenario (should have used a more visible colour for this example :D)
> Ability to highlight a pair's content

- smartparens.el
- test/smartparens-commands-test.el
Added sp-no-reindent-after-kill-indent-line-functions custom variable
which contains `indent-line-function's that shouldn't be reindented.
> Add support to avoid reindenting per indent-line-function

- smartparens.el
The large diff hides a trivial change: I wrapped the whole thing with `while-no-input`. This change makes for a *massive* usability improvement. For example my own theme contains a continuous sexp of nearly 1000 lines. Putting point on its edges would freeze the UI for multiple seconds. With this change there is no freeze at all, only the highlight takes a while to show up.
/edit: CI is all red, but judging from the build history that's not on me.
> Use while-no-input in show-pair-function.

- smartparens-c.el
- smartparens-config.el
- smartparens.el
I noticed that even though C is a major language, there is no specific configuration file.
For example, when I'm using `smartparens-strict-mode`, the `c-electric-backspace` is not remapped, which clears the closing parentheses despite `smartparens-strict-mode`.
I looked at below site and added the minimum necessary settings.
Of course, not all the pairs needed to edit C's files have been added, but having the files will make it easier for someone else to edit them.
I wrote `smartparens-c` based on `smartparens-clojure`, but if it violates the policy, please let me know. I'll modify.
ref: https://tuhdo.github.io/c-ide.html#orgheadline56
Or there may be another reason for not having a C specific configuration file. I am sorry in that case. Please close it.
> Integration of smartparens with c/cpp-mode

- smartparens.el
When a string is not properly formed, `sp-skip-into-string` can attempt to `(forward-char)` passed the end of the buffer.
E.g., with `point` at the beginning of the comment line in the following Lua code, eval `(sp-skip-into-string)` and you get an "End of buffer" error...
```lua
function foo()
-- point here
call_something()
-- this comment contains what looks like a string's delimiter
more code()
end
```
Perhaps this is because the `--` isn't recognised as a comment delimiter? I don't know. But a bounds-check in `sp-skip-into-string` seems appropriate nonetheless.
> added bounds check to sp-skip-into-string

- smartparens-config.el
The feature that implements both c-mode and c++-mode is called
cc-mode. There are no standalone c-mode and c++-mode features.
> Fix feature name for C-like modes

- smartparens.el
The code have already been using defvar-local (at the beginning of the
file there is a declaration of defvar-local for older Emacs versions),
but for some reason not everywhere. Let's fix that.
> smartparens.el: wire up defvar-local wherever suitable

- smartparens.el
This is a fix for https://github.com/Fuco1/smartparens/pull/958 when byte-compiling. The top level forms need to be wrapped in `eval-when-compile`.
See https://lists.gnu.org/archive/html/bug-gnu-emacs/2020-11/msg01056.html
> Fix compilation of sp--while-no-input

- sp-sublimetext-like.el
So, per [discussion here](https://github.com/Fuco1/smartparens/issues/1024#issuecomment-746215289), this is an opt-in configuration for parentheses autoinsertion, that supposed to have much less misses *(i.e. situations where a user has to manually delete the pair just inserted)* than the default "always insert a pair" behavior.
It is called sublimetext-like, because originally I have written this config following what SublimeText does. However that was years ago, so these days I don't know if it still matches. Anyway, AFAIR this editor has amazingly unobtrusive behavior for inserting pairs, so if someone decides to make further changes to the code to achieve even closer behavior, they're welcome.
> sp-sublimetext-like.el: provide SublimeText-like config

- smartparens.el
Similar to slime-repl-mode, sly-mrepl-mode can be added to the default
list of known lisp modes.
> Add sly-mrepl-mode to sp-lisp-modes

- smartparens.el
Recently, on Emacs master branch, a commit 55db25b257 was pushed to fix
Emacs bug [47150](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=47150). This bug was related to an incorrect implementation of
minibuffer-inactive-mode. It used to be the case that after the first
usage of the minibuffer, it stucks in minibuffer-inactive-mode, though
minibuffer-inactive-mode was intended for a completely different
purpose, and the minibuffer on the current frame should NOT be inactive.
The new design is to have two possible major modes for the minibuffer:
minibuffer-mode when it is active, and minibuffer-inactive-mode when it
is inactive.
> Also detect minibuffer-mode

- smartparens-scala.el
- test/smartparens-scala-test.el
Fixes #1098
This is not very robust: inserting double quotes inside a literal doesn't seem to count towards the closing lexeme, so there's no "typing yourself out of the literal". Still, it should be better than nothing. Any pointers would be appreciated.
> Add support for triple quoted string literals in Scala

- smartparens-scala.el
- test/smartparens-scala-test.el
Hello, 
thanks for awesome package, here is a fix for wrapping region with `{` in scala.
Without this fix result of `sp-test-scala-curly-wrap-indent` test would be: 
```
"if (true)\n{fo\n  o\n}"
```
Instead of correct
```
"if (true)\n{\n foo\n}"
```
> Scala wrap indented region correctly

- smartparens.el
[Fennel](https://fennel-lang.org/) is a Lisp like language that compiles to Lua
> add Fennel to lisp modes

- smartparens-ml.el
Thanks for the great package!
This adds more smart pairs for OCaml languages:
```ocaml
module ... end  (* module *)
sig .... end  (* signature *)
{| ... |}  (* multi-line string *)
[| ... |] (* array *)
```
> Add more pairs for OCaml

- Cask
- smartparens-config.el
- smartparens-swift.el
- test/smartparens-swift-test.el
- Add pairing for '<' and '>', adapted from the existing code for Rust.
- Add pairing for triple quotes
This is _heavily_ based on the existing Rust support, so I have also credited that code's author in my new file.
> Add basic 'swift-mode' support

- smartparens-c.el
There is a little-known [feature](https://www.doxygen.nl/manual/formulas.html) inside doxygen, which allows users to add inline formulas to the documentation:
```c
// The distance between \f$(x_1,y_1)\f$ and \f$(x_2,y_2)\f$ is 
// \f$\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}\f$.
```
This patch adds the corresponding pairs to the `sp-c-modes`.
> Add pairs for doxygen formulas in C / C++

- smartparens.el
It previously parsed the contents of load-history which made it sensitive to changes to what's in load-history. This fix uses feature-symbols instead (which uses load-history internally) which should be more stable than relying on load-history directly.
Fixes #1096
> Use feature-symbols to find functions for the cheat-sheet

- smartparens-ml.el
Thanks for the great package.
I added some pairs for OCaml in #1118, but I found my mistake. This fixes `module ... end` to `struct ... end`.
Thank you!
> Fix `module...end` to `struct..end` for OCaml

- smartparens-ruby.el
As of Emacs 29, `ruby-mode` and `ruby-ts-mode` are derived from `ruby-base-mode`. Have smartparens define behavior from the base mode to work with both
> Support `ruby-ts-mode`

- smartparens.el
The sp-pair function does not only add, but also remove or update pair
definitions. Make it immediately clear at the top of the
documentation. Later parts of the documentation refer to updating of
the definition and without mentioning that sp-pair can also update,
the documentation is confusing.
> Clarify sp-pair documentation

- smartparens-config.el
- smartparens-python.el
This has been done for the `elixir-ts-mode` before.  Maybe every tree-sitter powered modes, like `bash-ts-mode` or `c-ts-mode`, should be added as well?
> Add python-ts-mode (treesit) as an alias for python-mode

- smartparens-config.el
- smartparens-javascript.el
- smartparens.el
Adds the new Emacs 29+ `js-ts-mode` and `typescript/tsx-ts-mode` to the configs for `smartparent-javascript`. 
I also added `tsx-ts-mode` to `sp--html-modes` which  should address https://github.com/Fuco1/smartparens/issues/1168.
> Add support for js-ts-mode and typescript-ts-mode

- smartparens.el
Emacs 29 introduced treesitter programming modes. This updates the list of modes where a reindent shouldn't be performed after kill to take that into account.
> fix: don't indent after kill in python-ts-mode

- smartparens.el
`eval-when-compile' defines the alias symbol only at compile time and not when the program is loaded and thus results in a void error at runtime.
Fixes #1204
> Fix invalid alias definition for `syntax-class-to-char'

- smartparens.el
- test/smartparens-commands-test.el
This allows deleting empty sexps not only when they are completely empty (closing delimiter follows immediately after opening delimiter), but also if they only consist of white-space.
This is useful for modes where white-space is mandatory after/before delimiters, to get the same behavior for deleting empty sexps.
This also changes the return value of `sp-point-in-blank-sexp` to
return the beginning and ending positions of the enclosing regexp.
> Add customizable behavior allowing backward-delete of blank sexps

- smartparens-ruby.el
I'm not sure how to use sp-ruby-forward-sexp and sp-ruby-backward-sexp properly, but because I happened to find a misuse I'm submitting this.
> Use fboundp for functions

- smartparens-config.el
- smartparens.el
Require `smartparens-c` when `c-ts-mode` is loaded, and add `c-ts-mode` and `c++-ts-mode` to `sp-c-modes`.
> config for c-ts-mode and c++-ts-mode

- smartparens-pkg.el
- smartparens.el
MELPA recently stopped extracting dependencies from smartparens-pkg.el (see
https://github.com/melpa/package-build/commit/760cf53114a6f27e86bc87b44726ced34bcda0ea). In a fresh install (using `emacs --init-directory` pointed at a directory with just an init.el configuring MELPA, no other packages installed), `M-x package-install smartparens` does not install dash, which means smartparens does not work.
Try to fix it by copying the dependencies from smartparens-pkg.el to a Package-Requires header, which MELPA should still extract.
Drop the dependency on cl-lib while I'm there. This was needed in Emacs < 24, which smartparens no longer supports.
> Copy dependencies into smartparens.el for MELPA

- smartparens.el
- test/smartparens-commands-test.el
Fixes #1212 by ignoring the prefix syntax flag once point is inside the symbol. 
I've added a few tests that hopefully illustrate the issue/expected behaviour.
> fix: ignore prefix syntax not in prefix position

- smartparens-go.el
Add `go-ts-mode` to `smartparens-go.el`.
> Add go-ts-mode to smartparens-go.el
